# Generated by Django 4.2.6 on 2023-10-23 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("olt", "0002_usuario_setor_alter_usuario_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
