# Generated by Django 4.2.6 on 2023-10-23 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("olt", "0003_usuario_last_login"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
