"""alteração nas colunas da tabela status_log

Revision ID: 4b443a82656d
Revises: d45d92ca51d6
Create Date: 2023-11-13 16:42:09.370060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b443a82656d'
down_revision = 'd45d92ca51d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_selecionado', sa.String(length=160), nullable=True))
        batch_op.drop_column('ont_onu')
        batch_op.drop_column('equipamento')
        batch_op.drop_column('cx')
        batch_op.drop_column('fp')
        batch_op.drop_column('fs')
        batch_op.drop_column('cb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cb', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('fs', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('fp', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('cx', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('equipamento', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('ont_onu', sa.VARCHAR(length=4), nullable=True))
        batch_op.drop_column('cliente_selecionado')

    # ### end Alembic commands ###
