"""Mensagem inicial

Revision ID: d45d92ca51d6
Revises: 
Create Date: 2023-11-13 13:09:45.242623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45d92ca51d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provisionamento_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_logado', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rota_link', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('nome_cliente', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('equipamento', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('ont_onu', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('cb', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('fp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('cx', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('fs', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provisionamento_log', schema=None) as batch_op:
        batch_op.drop_column('fs')
        batch_op.drop_column('cx')
        batch_op.drop_column('fp')
        batch_op.drop_column('cb')
        batch_op.drop_column('ont_onu')
        batch_op.drop_column('equipamento')
        batch_op.drop_column('nome_cliente')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('rota_link')
        batch_op.drop_column('usuario_logado')

    # ### end Alembic commands ###
